Dev
vadim4ik99/LinkUP pull request #2
Opened 2022-08-12 09:11 UTC by vadim4ik99

work with model db

2022-08-12 09:47 UTC, bserefaniuk requested changes

2022-08-12 09:47 UTC, bserefaniuk commented on src/app.module.ts
> +          CategoryProductEntity, OrderProductEntity],
Для того щоб не перераховувати все можна прописати наступне:
`entities: [__dirname + '/**/*.{entity,view}.{ts,js}'],`

2022-08-12 09:47 UTC, bserefaniuk commented on src/main.ts
> +async function bootstrap():Promise<void> {
```suggestion
async function bootstrap(): Promise<void> {
```

2022-08-12 09:47 UTC, bserefaniuk commented on src/modules/user/services/user.service.ts
> +        private userRepository: UserRepository,
Відступи мають бути у два пробіли, поки підключення сервіса можна не вказувати, щоб не було unused

2022-08-12 09:47 UTC, bserefaniuk commented on src/modules/user/services/user.abstract.service.ts
> +  }
1. все у camelCase
2. це не відноситься до сервіса, залиш поки порожнім

2022-08-12 09:47 UTC, bserefaniuk commented on src/app.module.ts
> +          CategoryProductEntity, OrderProductEntity],
Щоб не прописувати все самостійно, можна таке зробити
`entities: [__dirname + '/**/*.{entity,view}.{ts,js}'],`

2022-08-12 09:47 UTC, bserefaniuk commented on src/modules/cart/dto/cart.dto.ts
> +export class CartDTO {
1. Обʼєкт продукта неможе бути описаний числом
2. Якщо це як список із пагінацією тоді тут мають бути якісь мета данні

2022-08-12 09:47 UTC, bserefaniuk commented on src/modules/categories/dto/categories.dto.ts
> +  private name: string;
1. Якщо це будуть приватні поля тоді як ми можемо це використати?
2. Потрібний ID
3. Картинка неможе бути опиисана як масив чисел

2022-08-12 09:47 UTC, bserefaniuk commented on src/modules/product/dto/product.dto.ts
> +export class ProductDTO {
ID, camelCase, correct types

2022-08-12 09:47 UTC, bserefaniuk commented on src/modules/product/services/product.abstract.service.ts
> +import type { CategoriesEntity } from 'src/modules/categories/entities/categories.entity';
src -> relative path

2022-08-12 09:47 UTC, bserefaniuk commented on src/modules/product/services/product.abstract.service.ts
> +  public abstract getCategoryProduct(id: string):Promise<CategoriesEntity[]>;
Залиш поки пустим, бо там багато моментів буде

2022-08-12 14:08 UTC, bserefaniuk requested changes
1. `common` module should have the same structure as the rest
2.

2022-08-12 14:08 UTC, bserefaniuk commented on src/modules/user/repositories/user.repositories.ts
> +@EntityRepository(UserEntity)
EntityRepository is deprecated, please, use 'extend' instead
ref: https://orkhan.gitbook.io/typeorm/docs/custom-repository

2022-08-12 14:08 UTC, bserefaniuk commented on src/modules/categories/entities/categories.entity.ts
> +  public createdAat!: Date;
typo

2022-08-12 14:08 UTC, bserefaniuk commented on src/modules/categories/entities/categories.entity.ts
> +  @OneToMany(() => CategoryProductEntity ,(catProd) => catProd.category)
```suggestion
  @OneToMany(() => CategoryProductEntity, (catProd) => catProd.category)
```

2022-08-12 14:08 UTC, bserefaniuk commented on src/modules/common/entities/images.entity.ts
> +  public  category!: CategoriesEntity;
```suggestion
  public category!: CategoriesEntity;
```

2022-08-12 14:08 UTC, bserefaniuk commented on src/modules/common/entities/images.entity.ts
> +  public size!: string;
number

2022-08-12 14:08 UTC, bserefaniuk commented on src/modules/common/entities/images.entity.ts
> +  public created_at!: Date;
camelCase

2022-08-12 14:08 UTC, bserefaniuk commented on src/modules/order/entities/order.entity.ts
> +    DELIVERED = 'deliverd'
fix count of spaces

2022-08-12 14:08 UTC, bserefaniuk commented on src/modules/cart/entities/cart.entity.ts
> +
Where is the reference to a user ?

2022-08-12 14:08 UTC, bserefaniuk commented on src/modules/cart/entities/cart.entity.ts
> +  public products!: ProductEntity[];
It's different relation as you designed, you have to use productId here

2022-08-12 14:08 UTC, bserefaniuk commented on src/modules/categories/entities/categories.entity.ts
> +  public images!: ImagesEntity[];
category can have only one image

2022-08-12 14:08 UTC, bserefaniuk commented on src/modules/categories/entities/categories.entity.ts
> +  public product!: ProductEntity;
a category does not relate to one product, it should not be here

2022-08-12 14:08 UTC, bserefaniuk commented on src/modules/common/entities/images.entity.ts
> +  public product!: ProductEntity;
product may have reference to this image but image is not required to be referenced to a product

2022-08-12 14:08 UTC, bserefaniuk commented on src/modules/common/entities/images.entity.ts
> +  public  category!: CategoriesEntity;
the same as product stuff

2022-08-12 14:08 UTC, bserefaniuk commented on src/modules/order/entities/order.entity.ts
> +  public orderProduct!: OrderProductEntity[];
```suggestion
  public orderProducts!: OrderProductEntity[];
```

2022-08-12 14:08 UTC, bserefaniuk commented on src/modules/product/entities/category-product.entity.ts
> +  public updated_at!: Date;
We do not need it

2022-08-12 14:08 UTC, bserefaniuk commented on src/modules/product/entities/order-product.entity.ts
> +  public updated_at!: Date;
remove it

2022-08-12 14:08 UTC, bserefaniuk commented on src/modules/product/entities/product.entity.ts
> +  public cart!: CartEntity;
I guess it should be one-to-many

2022-08-12 14:08 UTC, bserefaniuk commented on src/modules/product/entities/product.entity.ts
> +  public images!: ImagesEntity[];
a product should have one image

2022-08-12 14:08 UTC, bserefaniuk commented on src/modules/user/entities/user.entity.ts
> +import { OrderEntity } from 'src/modules/order/entities/order.entity';
replace src

2022-08-12 14:08 UTC, bserefaniuk commented on src/modules/user/entities/user.entity.ts
> +  public first_name!: string;
camelCase everywhere

2022-08-19 10:18 UTC, bserefaniuk requested changes
Модуль категорій я б відправив у комон (як такий видалити і перенести ентіті і репо у комон)

2022-08-19 10:18 UTC, bserefaniuk commented on src/modules/common/entities/images.entity.ts
> +  public updatedAt!: Date;
Нам це не потрібно, ми не будемо його оновлювати

2022-08-19 10:18 UTC, bserefaniuk commented on src/modules/common/entities/images.entity.ts
> +export class ImagesEntity {
Для більшої універсальності ми можемо його назвати як FileEntity

2022-08-19 10:18 UTC, bserefaniuk commented on src/modules/common/entities/images.entity.ts
> +  public user!: CategoriesEntity;
Файл не матиме обовʼязоквого посилання на категорію, юзера чи продукт. Тут звʼязок many-to-one

Проте такий варіант запису можливий
categories: CategoryEntity[]
...

2022-08-19 10:18 UTC, bserefaniuk commented on src/modules/categories/entities/categories.entity.ts
> +  public products!: ProductEntity[];
Цей звʼязок не потрібний оскільки ми маєто той що нище

2022-08-19 10:18 UTC, bserefaniuk commented on src/modules/categories/entities/categories.entity.ts
> +  public categoryProduct!: CategoryProductEntity[];
```suggestion
  public categoryProducts!: CategoryProductEntity[];
```

2022-08-19 10:18 UTC, bserefaniuk commented on src/modules/cart/entities/cart.entity.ts
> +  @OneToOne(() => UserEntity, (user) => user.cart)
тут теж ManyToOne

2022-08-19 10:18 UTC, bserefaniuk commented on src/modules/user/entities/user.entity.ts
> +  public image!: ImagesEntity;
```suggestion
  public avatar!: ImagesEntity;
```

2022-08-19 10:18 UTC, bserefaniuk commented on src/modules/user/entities/user.entity.ts
> +  @OneToOne(() => ImagesEntity, (image) => image.user)
many to one

2022-08-19 10:18 UTC, bserefaniuk commented on src/modules/product/entities/product.entity.ts
> +  @OneToOne(() => ImagesEntity, (image) => image.product)
many to one

2022-08-19 10:18 UTC, bserefaniuk commented on src/modules/product/entities/product.entity.ts
> +  public category!: CategoriesEntity;
Не потрібно

2022-08-19 10:18 UTC, bserefaniuk commented on src/modules/product/entities/product.entity.ts
> +  public categoryProduct!: CategoryProductEntity[];
```suggestion
  public categoryProducts!: CategoryProductEntity[];
```

2022-08-23 12:18 UTC, YuriiVasylyshyn reviewed
Зверни увагу на форматування, в цілому добре, продовжуй працювати далі

2022-08-23 12:18 UTC, YuriiVasylyshyn commented on src/modules/auth/services/auth.service.ts
> +  public async validateUser(email: string, pass: string): Promise<UserEntity> {
`override` missed

2022-08-23 12:18 UTC, YuriiVasylyshyn commented on src/modules/auth/services/auth.service.ts
> +  public async login(email: string): Promise<unknown> {
`override` missed again

2022-08-23 12:18 UTC, YuriiVasylyshyn commented on src/modules/user/services/user.service.ts
> +        private readonly usersRepository: Repository<UserEntity>,
багато пробілів, залишай лише два після абзацу, в тебе тут шість

```suggestion
    @Inject(UserRepository)
    private readonly usersRepository: Repository<UserEntity>,
```

2022-08-23 12:18 UTC, YuriiVasylyshyn commented on src/modules/user/services/user.service.ts
> +  public async findUser(email: string): Promise<UserEntity | null> {
`override`

2022-08-23 12:18 UTC, YuriiVasylyshyn commented on src/modules/user/services/user.service.ts
> +  public async createUser(userDto: Pick <UserDTO, 'email' | 'password'>): Promise<UserEntity> {
`override`

2022-08-23 12:18 UTC, YuriiVasylyshyn commented on src/modules/user/services/user.service.ts
> +import type { UserEntity } from '../entities/user.entity';
типи повинні бути знизу
```suggestion
import { BadRequestException, Inject, Injectable } from '@nestjs/common';
import { Repository } from 'typeorm';
import { UserRepository } from '../repositories/user.repository';
import { UserService } from './user.service.abstract';
import { genSalt, hash } from 'bcrypt';

import type { UserDTO } from '../dto/user.dto';
import type { UserEntity } from '../entities/user.entity';

```

2022-08-23 12:18 UTC, YuriiVasylyshyn commented on src/modules/auth/services/auth.service.ts
> +import { AuthService } from './auth.service.abstract';
```suggestion
import { Injectable, UnauthorizedException } from '@nestjs/common';
import { JwtService } from '@nestjs/jwt';
import { compare } from 'bcrypt';
import { UserServiceImpl } from 'src/modules/user/services/user.service';
import { AuthService } from './auth.service.abstract';

import type { UserEntity } from 'src/modules/user/entities/user.entity';
```

2022-08-23 12:18 UTC, YuriiVasylyshyn commented on src/modules/user/services/user.service.ts
> +    return await this.usersRepository.save(newUser);
в return, якщо функція асинхронна await не обовʼязковий, повертається тип проміс

```suggestion
    return this.usersRepository.save(newUser);
```

2022-08-29 12:51 UTC, YuriiVasylyshyn commented on src/modules/auth/services/auth.service.ts
> +    await this.sendTamplateEmail(user, EmailTamplate.Welcome);
typo, should be `sendEmailTemplate

2022-08-29 12:59 UTC, YuriiVasylyshyn commented on src/modules/auth/services/auth.service.ts
> +  public override async sendTamplateEmail (user: Pick<UserDTO,'email'>, tamplate: EmailTamplate): Promise<void> {
Template

2022-08-29 12:59 UTC, YuriiVasylyshyn commented on src/modules/auth/strategy/jwt.strategy.ts
> +  }
почитай - https://docs.nestjs.com/security/authentication#implementing-passport-local

цей метод не має сенсу, якщо він просто ретурнить дані які отримав, їх потрібно провалідувати, 
Створи метод, який би перевіряв наявність користувача в базі і чи його емейл підтверджено, якщо так тоді повертай вже те що тобі потрібно

Далі при створенні ендпоінтів ти повинен їх задекорувати там, де потрібно бути залогіненим - https://docs.nestjs.com/security/authentication#login-route

2022-08-29 12:59 UTC, YuriiVasylyshyn commented on src/modules/user/services/user.service.ts
> +import type { UpdateResult } from 'typeorm';
вниз

2022-08-29 18:13 UTC, vadim4ik99 commented on src/modules/auth/services/auth.service.ts
> +    await this.sendTamplateEmail(user, EmailTamplate.Welcome);
Don`t understand about typo , i have method sendMail from MailerService
 (method) MailerService.sendMail(sendMailOptions: ISendMailOptions): Promise<any>
but i can`t use Promise<any>, so what i must do return type in public override async singUp(userDto: Pick<UserDTO, 'email' | 'password'>): ?

2022-08-30 09:01 UTC, YuriiVasylyshyn commented on src/modules/auth/services/auth.service.ts
> +    await this.sendTamplateEmail(user, EmailTamplate.Welcome);
@vadim4ik99 typo означає посилка в слові. це не проблема в типу, слово темплейт не так пишеться англійською, через е

2022-08-30 10:17 UTC, YuriiVasylyshyn requested changes

2022-08-30 10:17 UTC, YuriiVasylyshyn commented on src/modules/auth/controllers/auth.controller.ts
> +  @Get('/confirmemail')
`  @Get('/email/confirm')`

2022-08-30 10:17 UTC, YuriiVasylyshyn commented on src/modules/auth/controllers/auth.controller.ts
> +  } */
```suggestion
  @Authorization()
  @Post('/reset-password')
  public override async resetPassword (
    @AuthUser() user: AuthUser,
    @Body() payload: Pick<UserDTO, 'password'>,
  ) {
    return this.authService.resetPassword(user, payload);
  } 
```

**Для залогованих користувачів не потрібно працювати з токенами в методі сервісів, краще це зробити один раз в guard**

`@Authorization()` - це guard який повинен витягувати з контексту токен, декодувати всю необхідну інфу і записувати в `request.user`. Ним огортатимеш ті ендпоінти, які потребують залогованого юзера. Імплементить `CanActivate` і повертає булеве значення, подивишся приклад документашки

https://docs.nestjs.com/guards

`@AuthUser() user: AuthUser` - це декоратор, який витягуватиме з `request.user` дані з необхідним інтерфейсом 

приклад

import { createParamDecorator } from '@nestjs/common';
import type { ExecutionContext } from '@nestjs/common';
import type { Request } from 'express';

export interface AuthUser {
  userId: string;
  email: string;
}

export const AuthUser = createParamDecorator(
  (_data: unknown, ctx: ExecutionContext) => {
    const request = ctx.switchToHttp().getRequest() as Request;
    return request.user ?? { };
  },
);

2022-08-31 06:50 UTC, vadim4ik99 commented on src/modules/auth/controllers/auth.controller.ts
> +  } */
"і записувати в request.user" а хіба це не завдання passport js?
Ось мій приклад @Authorization() , але він майже весь червоний, проблеми з request, а саме ще немає body і user https://prnt.sc/G6QaGOb-FGSL

export class AuthorizationGuard implements CanActivate {

  constructor(private readonly jwtService: JwtService) {}

  public canActivate(context: ExecutionContext): boolean | Promise<boolean> {
    const request = context.switchToHttp().getRequest;
    const { access_token } = request.body;
    try {
      const payload = this.jwtService.verify(access_token);
      request.user.email = payload.email;
      return true;
    } catch (e) { return false; }
  }

Така сама біда і з декоратором:

import type { ExecutionContext } from '@nestjs/common';
import { createParamDecorator } from '@nestjs/common';

export interface AuthUser {
    email: string;
    }

export const AuthUser = createParamDecorator(
  (_data: unknown, ctx: ExecutionContext) => {
    const request = ctx.switchToHttp().getRequest() as Request;
    return request.user as AuthUser; ------- user немає в Request
  },
);

2022-08-31 06:54 UTC, YuriiVasylyshyn commented on src/modules/auth/controllers/auth.controller.ts
> +  } */
@vadim4ik99 додай імпорт `import type { Request } from 'express';`

2022-08-31 06:59 UTC, YuriiVasylyshyn commented on src/modules/auth/controllers/auth.controller.ts
> +  } */
і діставай реквест отак - `const request = context.switchToHttp().getRequest<Request>();`

2022-08-31 06:59 UTC, YuriiVasylyshyn commented on src/modules/auth/controllers/auth.controller.ts
> +  } */
або так як в моєму прикладі

2022-08-31 07:18 UTC, YuriiVasylyshyn commented on src/modules/auth/controllers/auth.controller.ts
> +  } */
Можеш попробувати використати свій існуючий JWT guard, тоді створюєш декоратор на подобі такого

import { UseGuards, applyDecorators } from '@nestjs/common';
import { AuthJwtGuard } from '../guards/auth-jwt.guard';

type AuthorizationReturnType = ReturnType<typeof applyDecorators>

export const Authorization = (): AuthorizationReturnType => {
  const guardDecorators = [UseGuards(AuthJwtGuard/*, тут буде гуард для ролей */)];

  return applyDecorators(...guardDecorators);
};

тут заділ на майбутній таск, де тобі треба буде ще додавати ролі

2022-08-31 12:05 UTC, YuriiVasylyshyn requested changes
Порефактори і потести, чи все норм працює, якщо все норм і коли ти порефакториш зареквести ревʼю ще раз, я апрувну і змерджиш, наступне завадння зробиш окремим пр

2022-08-31 12:05 UTC, YuriiVasylyshyn commented on package.json
> +    "express-session": "^1.17.3",
remove if we don't use

2022-08-31 12:05 UTC, YuriiVasylyshyn commented on src/modules/auth/controllers/auth.controller.ts
> +import { AuthUser } from '../auth.decorator';
to the top

2022-08-31 12:05 UTC, YuriiVasylyshyn commented on src/modules/auth/guard/register.guard.ts
> +import type { CanActivate, ExecutionContext } from '@nestjs/common';
to bottom

2022-08-31 12:09 UTC, YuriiVasylyshyn commented on src/modules/auth/controllers/auth.controller.ts
>    public async signIn (@Body() userDto: Pick<UserDTO, 'email' | 'password'>): Promise<UserEntity> {
Pick won't work with Swagger, use only DTO (change everywhere)

2022-09-02 14:20 UTC, YuriiVasylyshyn requested changes

2022-09-02 14:20 UTC, YuriiVasylyshyn commented on src/modules/auth/controllers/auth.controller.ts
>    ): Promise<UserEntity> {
you should create `UserResDto` as a response type instead of entity with fields you want to return

2022-09-02 14:20 UTC, YuriiVasylyshyn commented on src/modules/auth/services/auth.service.ts
> +//import { MailService } from '../../mail/services/mail.service.abstract';
remove

2022-09-02 14:20 UTC, YuriiVasylyshyn commented on src/modules/auth/services/auth.service.ts
> +    //private readonly mailService: MailService,
remove

2022-09-02 14:20 UTC, YuriiVasylyshyn commented on src/modules/auth/services/auth.service.ts
> +    );*/
remove

2022-09-02 14:20 UTC, YuriiVasylyshyn commented on src/modules/auth/strategy/jwt.strategy.ts
> +import { UserEntity } from 'src/modules/user/entities/user.entity';
to the top

2022-09-02 14:20 UTC, YuriiVasylyshyn commented on src/modules/auth/strategy/jwt.strategy.ts
> +    private readonly userService: UserService,
```suggestion
    protected readonly _configService: ConfigService,
    private readonly _userService: UserService,
```

2022-09-02 14:20 UTC, YuriiVasylyshyn commented on src/modules/mail/services/mail.service.ts
> +import path from 'path';
top

2022-09-02 14:20 UTC, YuriiVasylyshyn commented on src/modules/auth/controllers/auth.controller.ts
> +import { UserEmailDTO } from '../../user/dto/user-email.dto';
top

2022-09-02 14:20 UTC, YuriiVasylyshyn commented on src/modules/auth/controllers/auth.controller.ts
>    ): Promise<UserEntity> {
in future it would be used in swagger documentation

2022-09-05 08:26 UTC, YuriiVasylyshyn requested changes

2022-09-05 08:26 UTC, YuriiVasylyshyn commented on src/modules/auth/auth.module.ts
> +  controllers: [authController],
```suggestion
  controllers: [AuthControllerImp],
```

2022-09-05 08:26 UTC, YuriiVasylyshyn commented on src/modules/product/product.module.ts
> +  controllers: [productController],
```suggestion
  controllers: [ProductControllerImp],
```

2022-09-05 08:26 UTC, YuriiVasylyshyn commented on src/modules/product/product.module.ts
> +};
remove this

2022-09-05 08:26 UTC, YuriiVasylyshyn commented on src/modules/auth/auth.module.ts
> +const authController = { provide: AuthController, useClass: AuthControllerImp };
remove this

2022-09-05 11:05 UTC, YuriiVasylyshyn approved these changes

2022-09-05 11:10 UTC, merged