level 1
vadim4ik99/LinkUP pull request #3
Opened 2022-09-06 12:29 UTC by vadim4ik99

2022-09-07 08:22 UTC, YuriiVasylyshyn requested changes

2022-09-07 08:22 UTC, YuriiVasylyshyn commented on package.json
> +    "typeorm:create": "npm run typeorm -- migration:create ./src/migrations/$npm_config_name",
ти бачив, що назва міграції створюється некоректна, тому попробуй по іншому, такоє генерувати міграції ми не будемо, як я казав, потрібно писати вручну
 
 ```suggestion
    "typeorm:generate": "npm run typeorm -- -d ./src/ormconfig.ts migration:generate ./src/migrations/$npm_config_name",
    "typeorm:create": "npm run typeorm -- migration:create  \“src/migrations/$npm_config_name\“",
```

2022-09-07 08:22 UTC, YuriiVasylyshyn commented on src/migrations/1662490748917-$npm_config_name.ts
> +}
не коректна назва

2022-09-07 08:22 UTC, YuriiVasylyshyn commented on src/modules/auth/guard/roles.guard.ts
> +import type { CanActivate, ExecutionContext } from '@nestjs/common';
type вниз

2022-09-07 08:22 UTC, YuriiVasylyshyn commented on src/modules/auth/strategy/local.strategy.ts
> +import { UserTypeEnum } from 'src/modules/user/entities/user.entity';
вверх

2022-09-07 08:22 UTC, YuriiVasylyshyn commented on src/modules/product/controllers/product.controller.ts
> +import { Authorization } from 'src/modules/auth/decorators/authorization.decorator';
вверх

2022-09-07 08:22 UTC, YuriiVasylyshyn commented on src/modules/user/dto/create-user-response.dto.ts
> +  public role!: UserTypeEnum;
як я вже казав тип повинен бути не обовʼязковим і по дефолту кастомер
```suggestion
  @isEnum(UserTypeEnum)
  public role?: UserTypeEnum;
```

ти імпортнув UserTypeEnum як тип, тому не працює

2022-09-07 08:22 UTC, YuriiVasylyshyn commented on src/modules/user/entities/user.entity.ts
> +  Costumer = 'costumer'
```suggestion
  Customer = 'customer'
```
в нас роль покупця а не костюмера ))

2022-09-07 08:22 UTC, YuriiVasylyshyn commented on src/modules/user/services/user.service.ts
> +      role: userDto.role,
зроби деструктуризацію дтошки, легше читається

const { email, password, role } = userDto;

2022-09-07 10:29 UTC, vadim4ik99 commented on package.json
> +    "typeorm:create": "npm run typeorm -- migration:create ./src/migrations/$npm_config_name",
Скільки варінтів не пробував, все одно назву не підтягує(

2022-09-07 13:10 UTC, YuriiVasylyshyn requested changes

2022-09-07 13:10 UTC, YuriiVasylyshyn commented on src/modules/user/dto/create-user-response.dto.ts
> +  public role?: UserTypeEnum;
чому ти забрав перевірку на енам?

2022-09-08 13:57 UTC, YuriiVasylyshyn requested changes
remove every /* eslint-disable no-console */
make every imported module as global

2022-09-08 13:57 UTC, YuriiVasylyshyn commented on src/@framework/decorators/auth.decorator.ts
> +/* eslint-disable no-console */
remove

2022-09-08 13:57 UTC, YuriiVasylyshyn commented on src/@framework/decorators/authorization.decorator.ts
> +/* eslint-disable no-console */
remove

2022-09-08 13:57 UTC, YuriiVasylyshyn commented on src/@framework/decorators/authorization.decorator.ts
> +  const guardDecorators = [UseGuards( JwtGuard, RoleGuard)];
```suggestion
  const guardDecorators = [UseGuards(JwtGuard, RoleGuard)];
```

2022-09-08 13:57 UTC, YuriiVasylyshyn commented on src/@framework/guard/roles.guard.ts
> +/* eslint-disable no-console */
remove

2022-09-08 13:57 UTC, YuriiVasylyshyn commented on src/@framework/strategy/jwt.strategy.ts
> +/* eslint-disable no-console */
remove

2022-09-08 13:57 UTC, YuriiVasylyshyn commented on src/modules/auth/controllers/auth.controller.ts
> +  //@UseGuards(RegisterGuard)
in order to reset password user must be authorized, why have you removed guard?

2022-09-08 13:57 UTC, YuriiVasylyshyn commented on src/modules/auth/services/auth.service.ts
> +    tamplate;
```suggestion
    template;
```

2022-09-08 13:57 UTC, YuriiVasylyshyn commented on src/modules/auth/services/auth.service.ts
> +    tamplate;
and how it works, can you explain?

2022-09-08 13:57 UTC, YuriiVasylyshyn commented on src/modules/product/entities/product.entity.ts
> +  @Column({ nullable: true })
you should create a migration for all entity changes

2022-09-08 13:57 UTC, YuriiVasylyshyn commented on src/modules/product/product.module.ts
> +    AuthModule,
you don't need it here, because you marked this module as global

2022-09-08 13:57 UTC, YuriiVasylyshyn commented on src/modules/user/services/user.service.ts
>    public override async findUser(
you can make this method as private if you don't use it outside service, example:
```suggestion
  private async _findUser(
```

2022-09-08 14:35 UTC, vadim4ik99 commented on src/modules/auth/services/auth.service.ts
> +    tamplate;
Дійсно щось запутався, спочатку юзер заходить на /recovery , та вказує свій email, в цей час я генерую йому токін і відправляю лист с токеном(хоча можно і без листа) я урл ніяк потім не перевіряю. Далі він переходить на /reset-password , так як в нього вже є токен з минулого шагу @UseGuards(JwtGuard) його пропустить , і залишилось в нього взяти тільки новий пароль.

2022-09-08 14:43 UTC, YuriiVasylyshyn commented on src/modules/auth/services/auth.service.ts
> +    tamplate;
добре, видали тоді цей рядок

2022-09-09 07:05 UTC, YuriiVasylyshyn approved these changes

2022-09-15 08:38 UTC, merged